---

- name: Pre install
  hosts: all
  become: yes

  tasks:
    - block:
      - name: Update apt cache
        apt:
          update_cache: yes

      - name: Update all system packages
        apt:
          upgrade: dist

      - name: Install base system packages
        apt:
          name: '{{ common_packages }}'
          state: present
